"""Standalone autoharness primitives."""

from .adapters import (
    AdapterCapabilityProfile,
    AdapterStagingProfile,
    AdapterStagingSignal,
    BenchmarkAdapter,
    BenchmarkInvocation,
    BenchmarkRunResult,
    TaskIdentityProfile,
    get_adapter,
    implemented_adapter_ids,
    list_adapters,
)
from .autonomy import AutonomyMode, AutonomyPolicy, policy_for_mode
from .benchmarks import (
    BenchmarkAdapterSpec,
    benchmark_catalog_entry,
    benchmark_catalog,
    recommended_v1_adapter_ids,
)
from .campaigns import CampaignEvaluatorPolicy, PromotionPolicy, TrackBenchmarkPolicy, TrackConfig
from .editing import (
    EditApplicationResult,
    EditOperation,
    EditPlan,
    EditRestoreResult,
    apply_edit_plan,
    edit_plan_from_dict,
    start_edit_session,
)
from .interventions import Intervention
from .tracking import (
    BenchmarkRecord,
    ChampionManifest,
    PromotionRecord,
    create_promotion_record,
    create_benchmark_record,
    load_benchmark_record,
    load_champion_manifest,
    load_promotion_policy,
    load_track_policy,
    load_workspace,
    load_workspace_state,
    next_iteration_id,
    persist_benchmark_record,
    persist_champion_manifest,
    persist_promotion_policy,
    persist_promotion_record,
    persist_track_config,
    persist_track_policy,
    persist_workspace_track,
    promotion_policy_path,
    save_workspace,
    track_policy_path,
    track_config_path,
    workspace_config_path,
    resolve_workspace_dir,
    update_state_after_promotion,
    update_state_after_iteration,
    write_iteration_artifacts,
)
from .staging import StagingContext, create_copy_stage, rewrite_config_for_stage
from .staging import ResolvedStagingDecision, resolve_staging_decision
from .stages import StagePolicy, apply_stage_overrides, evaluate_stage_result, stage_policy_for
from .stages import compare_against_baseline
from .stats import (
    mean_confidence_interval,
    paired_mean_confidence_interval,
    wilson_interval,
    z_value,
)
from .validation import aggregate_validation_runs, build_repeated_configs, run_validation
from .workspace import WorkspaceConfig, WorkspaceState

__all__ = [
    "BenchmarkAdapter",
    "AutonomyMode",
    "AutonomyPolicy",
    "AdapterStagingProfile",
    "AdapterStagingSignal",
    "AdapterCapabilityProfile",
    "BenchmarkAdapterSpec",
    "BenchmarkInvocation",
    "BenchmarkRecord",
    "ChampionManifest",
    "BenchmarkRunResult",
    "CampaignEvaluatorPolicy",
    "EditApplicationResult",
    "EditOperation",
    "EditPlan",
    "EditRestoreResult",
    "Intervention",
    "PromotionRecord",
    "PromotionPolicy",
    "TrackBenchmarkPolicy",
    "ResolvedStagingDecision",
    "StagePolicy",
    "StagingContext",
    "TaskIdentityProfile",
    "TrackConfig",
    "WorkspaceConfig",
    "WorkspaceState",
    "apply_edit_plan",
    "apply_stage_overrides",
    "benchmark_catalog",
    "benchmark_catalog_entry",
    "compare_against_baseline",
    "create_benchmark_record",
    "create_promotion_record",
    "create_copy_stage",
    "edit_plan_from_dict",
    "get_adapter",
    "implemented_adapter_ids",
    "load_benchmark_record",
    "load_champion_manifest",
    "load_promotion_policy",
    "load_track_policy",
    "load_workspace",
    "load_workspace_state",
    "list_adapters",
    "next_iteration_id",
    "persist_benchmark_record",
    "persist_champion_manifest",
    "persist_promotion_policy",
    "persist_promotion_record",
    "persist_track_config",
    "persist_track_policy",
    "persist_workspace_track",
    "policy_for_mode",
    "recommended_v1_adapter_ids",
    "promotion_policy_path",
    "save_workspace",
    "track_policy_path",
    "track_config_path",
    "workspace_config_path",
    "resolve_workspace_dir",
    "resolve_staging_decision",
    "rewrite_config_for_stage",
    "aggregate_validation_runs",
    "build_repeated_configs",
    "evaluate_stage_result",
    "mean_confidence_interval",
    "paired_mean_confidence_interval",
    "run_validation",
    "stage_policy_for",
    "start_edit_session",
    "update_state_after_promotion",
    "update_state_after_iteration",
    "wilson_interval",
    "write_iteration_artifacts",
    "z_value",
]
